fix: [SONIC-169] add git & alphabetize installed packages in Dockerfile
Due to following error on deploy:

    Collecting commercetools@ git+https://github.com/edx/commercetools-python-sdk.git@36639f4a196d7fc0daecf914ee46f42229087abb (from -r requirements/production.txt (line 70))
      Cloning https://github.com/edx/commercetools-python-sdk.git (to revision 36639f4a196d7fc0daecf914ee46f42229087abb) to /tmp/pip-install-u2dcvnx4/commercetools_cdad0154d7824963bfdfe8c00e11493f
      ERROR: Error [Errno 2] No such file or directory: 'git' while executing command git version
    ERROR: Cannot find command 'git' - do you have 'git' installed and in your PATH?
    The command '/bin/sh -c pip install -r requirements/production.txt' returned a non-zero code: 1